### ISSUE TITLE
Questions about StaticMain.cpp

### ISSUE THREAD

**Issue by ghost** [banach-space/llvm-tutor#18]
Hello Andrzej,

I have some questions about [StaticMain.cpp](https://github.com/banach-space/llvm-tutor/blob/master/tools/StaticMain.cpp):
1. In function `countStaticCalls`, you added an instance of `StaticWrapper` to the `ModulePassManager`. It seems that the tool is an *analysis* tool (in the sense that it doesn't *transform* any units of IR), so why we are wrapping our analysis pass (i.e., `StaticCallCounter`) inside `StaticWrapper` (which is derived from `PassInfoMixin`)?
2. Why just registering `StaticCallCounter` (which is derived from `AnalysisInfoMixin`) to `ModuleAnalysisManager` is not enough?
3. If we have to explicitly call `MAM.getResult<StaticCallCounter>(M)`, why we didn't call it inside of a pass derived from `AnalysisInfoMixin` (instead we are calling it from `StaticWrapper` which is derived from `PassInfoMixin`)
4. How can I write my own *transformation pass* as a standalone tool? Which parts of the [StaticMain.cpp](https://github.com/banach-space/llvm-tutor/blob/master/tools/StaticMain.cpp) should be changed?

Thank you very much.

Cheers,
Amir

**Comment by banach-space** [comment]
Hi @khordadi ,

Thank you for your question! 

Basically, with New Pass Manager an analysis pass (e.g. `StaticCallCounter`) will not be run unless something (i.e. other pass) requests the results that it could generate by calling [getResult](https://github.com/banach-space/llvm-tutor/blob/e164b8f0194b5bd787bed138dccc604f5bdc42b0/tools/StaticMain.cpp#L50) (there might be other mechanisms for this that I am not aware of). In other words, if an analysis is not required/requested, why bother running it (i.e. generating the results)? I think that this answers Q1 and Q2.

As for Q3, I created an instance of [ModulePassManager](https://github.com/banach-space/llvm-tutor/blob/e164b8f0194b5bd787bed138dccc604f5bdc42b0/tools/StaticMain.cpp#L58) to register the transformation passes that I want to run (that's something that you control explicitly, e.g. through [MPM.run](https://github.com/banach-space/llvm-tutor/blob/e164b8f0194b5bd787bed138dccc604f5bdc42b0/tools/StaticMain.cpp#L74)). So:
* first you specify a transformation pass that you want to run (controlled explicitly)
* inside your transformation passes you can request results from your analysis pass (controlled implicitely)

Q4: this would be as simple as using a transformation pass instead of an analysis pass :)

Bear in mind that `StaticMain.cpp` is just a simplified illustration. `StaticCCWrapper` was added to create a transformation pass that can be run explicitly via `MPM.run`. But it's not really a transformation pass because it does not really transform anything. That's fine - it's a dummy transformation pass (i.e. wrapper). 

Does this make sense?

Andrzej

**Comment by khordadi** [comment]
Andrzej,

That was very helpful!

Thank you very much,
Amir
