### ISSUE TITLE
replace dataype

### ISSUE THREAD

**Issue by ArunaKote** [banach-space/llvm-tutor#24]
I want to write a pass which replaces float datatype with int.To achieve this ,How can I replace a datatype in .cpp file.

Thank You

**Comment by banach-space** [comment]
Hi, thank you for your question!

I replied to a similar question on LLVM's discourse: https://llvm.discourse.group/t/new-llvm-pass/2499. 

As this is a general LLVM question (rather than specific to **llvm-tutor**), I will close this issue and suggest that we continue the discussion on discourse. This way more people can participate (there's more traffic on discourse than here).

Kind regards,
Andrzej
